coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import path,include

#Elementos para que funcione las imagenes
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("products/",include("products.urls")),
    path("usuarios/",include("users.urls")),
    path("pedidos/", include("orders.urls")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

coffee_shop/orders/urls.py
from django.urls import path
#from django.contrib.auth.views import LogoutView
from .views import MyOrderView,CreateOrderProductView


urlpatterns = [
     path("misOrdenes/", MyOrderView.as_view(), name="misOrdenes"),
     path('agregar-producto/',CreateOrderProductView.as_view(),name='addProduct'),
]

coffee_shop/products/urls.py
from django.urls import path
from .views import ProductFormView,ProductListView,ProductListAPI

urlpatterns = [
    path('',ProductListView.as_view(),name="list_products"),
    path('api/',ProductListAPI.as_view(),name="list_products_api"),
    path('agregar/', ProductFormView.as_view(),name="add_product"),

]

coffee_shop/users/urls.py
from django.urls import path
#from django.contrib.auth.views import LogoutView
from .views import UsersListView,ClosedUser,RegisterView

urlpatterns = [
   path('',UsersListView.as_view(),name="login"),
   path('logout/',ClosedUser.as_view(),name="logout"),
   path('register/',RegisterView.as_view(),name="register"),
]

coffee_shop/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    is_activate=models.BooleanField(default=True)
    order_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order: {self.id} - by: {self.user}"

class OrderProduct(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.PositiveIntegerField()

    def __str__(self):
        return f"{self.order} - {self.product} - {self.quantity}"

coffee_shop/products/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name=models.TextField(max_length=100,verbose_name="Nombre")
    description=models.TextField(max_length=200,verbose_name="Descripción")
    price=models.DecimalField(max_digits=8,decimal_places=2,verbose_name="Precio")
    available=models.BooleanField(default=True,verbose_name="Disponible")
    photo=models.ImageField(upload_to="logos",null=True,blank=True,verbose_name="Foto")

    def __str__(self):
        return f"{self.name}"

coffee_shop/users/models.py
from django.db import models

# Create your models here.

coffee_shop/orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct

class OrderProductForm(ModelForm):
    class Meta():
        model=OrderProduct
        fields=['product', 'quantity']

coffee_shop/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.Form):
    name=forms.CharField( max_length=100,label="Nombre")
    description=forms.CharField(max_length=200,label="Descripción")
    price=forms.DecimalField(max_digits=8,decimal_places=2,label="Precio")
    available=forms.BooleanField(initial=True,required=False,label="Disponible")
    photo=forms.ImageField(label="Foto",required=False)

    #creacion de un producto desde la data que recibimos de un formulario
    def save(self):
        Product.objects.create(
            name=self.cleaned_data["name"],
            description=self.cleaned_data["description"],
            price=self.cleaned_data["price"],
            available=self.cleaned_data["available"],
            photo=self.cleaned_data["photo"],
        )

coffee_shop/orders/views.py
from django.views.generic import DetailView,CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Order
from .forms import OrderProductForm

# Create your views here.

class MyOrderView(DetailView,LoginRequiredMixin):
    model=Order
    template_name="orders/myOrder.html"
    context_object_name = "orders"

    def get_object(self, queryset=None):
        return Order.objects.filter(is_activate=True,user=self.request.user).first()


class CreateOrderProductView(CreateView,LoginRequiredMixin):
    form_class=OrderProductForm
    template_name="orders/create_order_product.html"
    success_url=reverse_lazy("misOrdenes")

    def form_valid(self, form):
        order,_=Order.objects.get_or_create(
            is_activate=True,
            user=self.request.user,
        )
        form_instance_order=order
        form_instance_quantity=1
        form.save()
        return super().form_valid(form)

coffee_shop/products/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import ProductForm
from .models import Product

from rest_framework.views import APIView
from .serializer import ProductSerializer
from rest_framework.response import Response
# Create your views here.

class ProductFormView(generic.FormView):
    template_name="products/add_products.html"
    form_class=ProductForm
    success_url=reverse_lazy("add_product")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ProductListView(generic.ListView):
    model=Product
    template_name="products/list_view.html"
    context_object_name="products"

class ProductListAPI(APIView):
    authetication_classes=[]
    permission_classes=[]

    def get(self,request):
        products=Product.objects.all()
        serializer=ProductSerializer(products,many=True)
        return Response(serializer.data)

coffee_shop/users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView,LogoutView

#Para el registro
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


class UsersListView(LoginView):
  template_name="users/login.html"

#para que el boton cerrar sesion redirija a esa Url
class ClosedUser(LogoutView):
    next_page="list_products"

class RegisterView(generic.CreateView):
    form_class=UserCreationForm
    template_name="users/register.html"
    success_url=reverse_lazy("login")

coffee_shop/orders/templates/orders/create_order_product.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h2>create order product.html</h2>

  {% block contenidoBase %}

  <div class="max-w-lg mx-auto mt-10">
    <h2 class="text-2xl font-bold text-center mb-4">Agregar Producto a la Orden</h2>

    <form method="post" action="{% url 'misOrdenes'%}">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Agregar Producto
        </button>
    </form>
</div>

  {% endblock contenidoBase %}

</body>
</html>

coffee_shop/orders/templates/orders/myOrder.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block titulo %}
    <title>Mis Ordenes</title>
  {% endblock titulo %}
</head>
<body>
  <h2>myOrder.html</h2>
  {% block contenidoBase %}
<div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
    <h2 class="text-2xl font-bold mb-4">Detalles de la Orden</h2>
    <div class="mb-2">
        <span class="text-lg font-semibold">Usuario: </span>
        <span class="text-lg">{{ orders.user.username|title }}</span>
    </div>
    <div class="mb-2">
        <span class="text-lg font-semibold">Fecha de la Orden: </span>
        <span class="text-lg">{{ orders.order_date|date:"F j, Y H:m" }}</span>
    </div>

    <div class="mt-6">
        <h3 class="text-xl font-bold mb-2">Artículos en tu orden:</h3>
        {% for product_order in orders.orderproduct_set.all %}
            <div class="flex justify-between items-center py-2 border-b">
                <div class="text-lg">{{ product_order.product.name }}</div>
                <div class="text-lg font-semibold">{{ product_order.product.price }}</div>
            </div>
        {% empty %}
            <div class="text-red-500">No hay artículos en tu orden</div>
        {% endfor %}
    </div>
</div>

<!-- Botón para volver a la página de inicio -->
<div class="mt-4">
    <a href="#" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
        Volver a la Página de Inicio
    </a>
</div>

{% endblock contenidoBase %}

</body>
</html>

coffee_shop/products/templates/products/add_products.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Todo correcto</h1>

    <form action="{% url 'add_product' %}" method="post">
      {% csrf_token %} {{form.as_p}}

      <button type="submit">Agregar</button>
    </form>
  </body>
</html>

coffee_shop/products/templates/products/list_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% extends "base.html" %}

    {% block titulo %}
    <title>Productos</title>
    {% endblock titulo %}


  </head>
  <body>
    {% block subtitle %}
    {% endblock subtitle %}

    {% block contenidoBase %}

    <div class="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4"> <!-- Grid con 4 columnas en pantallas grandes -->
      {% for product in products %}
      <div class="border border-gray-100 rounded-tr-3xl overflow-hidden shadow-md"> <!-- Contenedor del producto -->
        <form action="{% url 'addProduct' %}" method="post" class="relative">
          {% csrf_token %}
          <input type="hidden" name="product" value="{{product.id}}">

          <!-- Etiqueta de precio -->
          <span class="absolute -right-px -top-px rounded-bl-3xl rounded-tr-3xl bg-rose-600 px-6 py-4 font-medium uppercase tracking-widest text-white">
            ${{ product.price }}
          </span>

          <!-- Imagen del producto -->
          {% if product.photo %}
          <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="h-56 w-full object-cover rounded-tr-3xl">
          {% endif %}

          <!-- Información del producto -->
          <div class="p-4 text-center">
            <strong class="text-xl font-medium text-gray-900"> {{ product.name }} </strong>

            <p class="mt-2 text-sm text-gray-700">
              {{ product.description }}
            </p>

            <!-- Botón para agregar al carrito -->
            <button type="submit" class="mt-4 block w-full rounded-md border border-indigo-900 bg-indigo-900 px-5 py-3 text-sm font-medium uppercase tracking-widest text-white transition-colors hover:bg-white hover:text-indigo-900">
              Agregar al carrito
            </button>
          </div>
        </form>
      </div>
      {% endfor %}
    </div>

    {% endblock contenidoBase %}


    {% comment %}

     {% block contenidoBase %}
     <ul>
       {%for product in products %}
       <li>

         <p>{{product.name}}</p>
         <p>{{product.price}} $</p>

         {% if product.photo %}
         <img src="{{ product.photo.url }}" alt="{{product.name}}" style="max-height: 100px;"/>
         {% endif %}
       </li>
       {% endfor %}
     </ul>

     {% endblock contenidoBase %}

    {% endcomment %}




  </body>
</html>

coffee_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% block titulo %}
  <title></title>
  {% endblock titulo %}
  <script src="https://cdn.tailwindcss.com"></script>

</head>
<body>
  <header class="bg-orange-50">
    <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8" style="margin-bottom: 25px;">
        <div class="flex items-center justify-between">

            <!-- Saludo en el margen izquierdo -->
            {% if user.is_authenticated %}
            <div class="flex items-center">
                <h2 class="text-2xl font-bold text-gray-900 sm:text-3xl">Hello {{ user.username }}</h2>
            </div>
            {% endif %}

            <!-- Título centrado -->
            <div class="flex-grow text-center">
                <h1 class="text-3xl font-bold text-gray-900">Coffee Shop</h1>
            </div>

            <!-- Botones en el margen derecho -->
            <div class="flex items-center gap-4">
                {% if user.is_authenticated %}
                <!-- Botón "Mi pedido" -->
                <form action="#" method="post">
                    <button
                        class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                        <span
                            class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                            Mi pedido
                        </span>
                    </button>
                </form>

                <!-- Botón "Cerrar Sesión" -->
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button
                        class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
                        type="submit">
                        <span
                            class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                            Cerrar Sesión
                        </span>
                    </button>
                </form>
                {% else %}
                <!-- Botón "Mi pedido" -->
                <button
                    class="relative inline-flex items-center justify-center p-0.5 mb-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                    <span
                        class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                        Mi pedido
                    </span>
                </button>

                <!-- Botón "Iniciar Sesión" -->
                <a class="relative inline-flex items-center justify-center p-0.5 mb-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
                    href="{% url 'login' %}">
                    <span
                        class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                        Iniciar Sesión
                    </span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>




  <div class="container mx-auto px-4" >
    {% block contenidoBase %}

    {% endblock contenidoBase %}
  </div>


</body>
</html>

coffee_shop/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% extends "base.html" %}

  {% block titulo %}
  <title>Login 2.9</title>
  {% endblock titulo %}

</head>
<body>
  {% block contenidoBase %}

  <div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-lg">
      <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">Iniciar Sesión</h1>

      <!-- El action="#" se reemplaza con la URL del formulario -->
      <form action="{% url 'login' %}" method="post" class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-lg sm:p-6 lg:p-8" style="background-color: #a2d2ff;">
        {% csrf_token %}

        <!-- Esta línea incluye el formulario que se ha pasado desde la vista -->
        <input
        type="text"
        name="username"
        class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
        placeholder="Usuario"
      />

      <input
        type="password"
        name="password"
        class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
        placeholder="Contraseña"
      />

        <button
          type="submit"
          class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
        >
          Ingresar
        </button>

        <p class="text-center text-sm text-gray-500">
          ¿No tienes una cuenta?
          <a class="underline" href="{% url 'register' %}">Regístrate</a>
        </p>
      </form>
    </div>
  </div>


  {% endblock contenidoBase %}

</body>
</html>

coffee_shop/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>

    <div class="max-w-md mx-auto mt-10 bg-green-50 p-6 rounded-lg shadow-md" style="margin-bottom: 65px;">
        <h2 class="text-2xl font-bold text-center">Crear una cuenta</h2>

        <form method="post" class="mt-6 space-y-6">
          {% csrf_token %}

          <!-- Username -->
          <div>
            <label for="id_username" class="block text-sm font-medium text-gray-700">Usuario</label>
            <input type="text" name="username" id="id_username"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            <p class="text-gray-600 text-sm mt-2">
              Obligatorio. Longitud máxima de 150 caracteres. Solo puede estar formado por letras, números y los caracteres
              @/./+/-/_.
            </p>
            {% if form.username.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.username.errors }}</p>
            {% endif %}
          </div>

          <!-- Email -->
          <div>
            <label for="id_email" class="block text-sm font-medium text-gray-700">Email</label>
            <input type="email" name="email" id="id_email"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value="{{ form.email.value }}">
            {% if form.email.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.email.errors }}</p>
            {% endif %}
          </div>

          <!-- First Name -->
          <div>
            <label for="id_first_name" class="block text-sm font-medium text-gray-700">Nombre</label>
            <input type="text" name="first_name" id="id_first_name"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value="{{ form.first_name.value }}">
            {% if form.first_name.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.first_name.errors }}</p>
            {% endif %}
          </div>

          <!-- Last Name -->
          <div>
            <label for="id_last_name" class="block text-sm font-medium text-gray-700">Apellido</label>
            <input type="text" name="last_name" id="id_last_name"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value="{{ form.last_name.value }}">
            {% if form.last_name.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.last_name.errors }}</p>
            {% endif %}
          </div>

          <!-- Password -->
          <div>
            <label for="id_password1" class="block text-sm font-medium text-gray-700">Contraseña</label>
            <input type="password" name="password1" id="id_password1"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            <p class="text-gray-600 text-sm mt-2">
              Su contraseña no puede ser similar a otros componentes de su información personal.<br>
              Su contraseña debe contener por lo menos 8 caracteres.<br>
              Su contraseña no puede ser una contraseña usada muy comúnmente.<br>
              Su contraseña no puede estar formada exclusivamente por números.
            </p>
            {% if form.password1.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.password1.errors }}</p>
            {% endif %}
          </div>

          <!-- Confirm Password -->
          <div>
            <label for="id_password2" class="block text-sm font-medium text-gray-700">Confirmar Contraseña</label>
            <input type="password" name="password2" id="id_password2"
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            {% if form.password2.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.password2.errors }}</p>
            {% endif %}
          </div>

          <!-- Submit Button -->
          <div>
            <button type="submit"
              class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              Registrar
            </button>
          </div>
        </form>
      </div>






</body>
</html>